### ISSUE TITLE
facing isssue after runing it and checking status 

### ISSUE THREAD

**Issue by Tejus2223** [lsgdefault/Fake-Profile-Detection-System-Using-ML-ANN#2]
![Screenshot 2024-11-21 230642](https://github.com/user-attachments/assets/1f37905b-e84c-438a-8599-4199c732ca05)

**Comment by lsgdefault** [comment]
> ![Screenshot 2024-11-21 230642](https://github.com/user-attachments/assets/1f37905b-e84c-438a-8599-4199c732ca05)
> 

You have to add your own Instagram login and update Instagram api

**Comment by Tejus2223** [comment]
sir where add instagram api can you help through it
