### ISSUE TITLE
sir where add instagram api can you help through it

### ISSUE THREAD

**Issue by Tejus2223** [lsgdefault/Fake-Profile-Detection-System-Using-ML-ANN#3]
sir where add instagram api can you help through it
![image](https://github.com/user-attachments/assets/b9bd40c5-3d7f-46da-91c3-45e85f80616f)

**Comment by lsgdefault** [comment]
The Instagram API previously utilized for this project has been deprecated. As this project is no longer maintained, you will need to source and integrate an alternative solution independently.
