### ISSUE TITLE
> ![Screenshot 2024-11-21 230642](https://github.com/user-attachments/assets/1f37905b-e84c-438a-8599-4199c732ca05)

### ISSUE THREAD

**Issue by Tejus2223** [lsgdefault/Fake-Profile-Detection-System-Using-ML-ANN#4]
> ![Screenshot 2024-11-21 230642](https://github.com/user-attachments/assets/1f37905b-e84c-438a-8599-4199c732ca05)
> 

You have to add your own Instagram login and update Instagram api

_Originally posted by @lsgdefault in https://github.com/lsgdefault/Fake-Profile-Detection-System-Using-ML-ANN/issues/2#issuecomment-2491994326_

**Comment by lsgdefault** [comment]
The Instagram API previously utilized for this project has been deprecated. As this project is no longer maintained, you will need to source and integrate an alternative solution independently.
